### ISSUE TITLE
Wrong drop location when page is scrolled

### ISSUE THREAD

**Issue by Remigius2011** [fatlinesofcode/ngDraggable#123] opened 2015-04-01 07:02 UTC
Assume we have a set of vertically arranged drop zones, e.g. as a result of an ng-repeat, that have ids corresponding to their index, e.g. id-0, id-1 etc. As long as the page is not scrolled, the drop goes to the correct element. As soon as the page is scrolled, the drop goes to a shifted element, e.g. to element id-5 instead of id-3, where it was dropped. This comes from the method hitTest (ngDraggable.js, line 342). There, the coordinates mouseX and mouseY come from an event's pageX and pageY, which are relative to the page origin, whereas the rectangle, against which they are tested, are relative to the viewport (see description of getBoundingClientRect). This can be fixed by changing the hitTest as follows:

    var hitTest = function(x, y) {
        var bounds = element[0].getBoundingClientRect();// ngDraggable.getPrivOffset(element);
        x -= document.body.scrollLeft + document.documentElement.scrollLeft;
        y -= document.body.scrollTop + document.documentElement.scrollTop;
        bounds.right = bounds.left + element[0].offsetWidth;
        bounds.bottom = bounds.top + element[0].offsetHeight;
        return  x >= bounds.left
                && x <= bounds.right
                && y <= bounds.bottom
                && y >= bounds.top;
    };

This transforms the mouse location to viewport coordinates and checks them correctly against the (possibly shifted) rectangle.
I hope this information is sufficiently clear to fix the problem. Unfortunately my project is too complex to serve as an example, but if absolutely necessary, I could provice a minimal project that reproduces the problem and/or a pull request with the fix.

**Comment by Cinetik** [comment] 2015-04-01 07:05
fix have been merged in the 0.1.4. Time to git pull master :)

**Comment by Remigius2011** [comment] 2015-04-01 11:10
@Cinetik thanks for the incredibly fast reaction. using $window is probably better (i.e. ng-ish) than my suggestion. However, I think, you only have to adjust the mouse location (y and y) but not the bounds rectangle's right and bottom:

    var hitTest = function(x, y) {
        var bounds = element[0].getBoundingClientRect();// ngDraggable.getPrivOffset(element);
        bounds.right = bounds.left + element[0].offsetWidth;
        bounds.bottom = bounds.top + element[0].offsetHeight;
        x -= $window.pageXOffset;
        y -= $window.pageYOffset;
        return  x >= bounds.left
                && x <= bounds.right
                && y <= bounds.bottom
                && y >= bounds.top;
    };

the bounds rectangle should be left entirely in the viewport coordinate system, otherwise the rectangle might shrink to negative size.

**Comment by Remigius2011** [comment] 2015-04-01 11:19
see also:

http://stackoverflow.com/questions/16618785/ie8-alternative-to-window-scrolly
http://www.jacklmoore.com/notes/mouse-position/

(my solution was the inverse of the calculation of pageX/pageY suggested by Jack Moore)

**Comment by Cinetik** [comment] 2015-04-01 11:32
Seems coherent to me. Have you tested it ? If it works, send a pull request :+1:

**Comment by Remigius2011** [comment] 2015-04-01 11:34
I've tested my original suggestion and it worked for my case. If you like,
I can try to produce a minimal project that displays the error and
validates the fix.

**Comment by Cinetik** [comment] 2015-04-01 11:35
Let's do that then.

**Comment by Remigius2011** [comment] 2015-04-01 12:27
Ok, here it is:

https://github.com/Remigius2011/dragproblem

It is self-contained and contains my modified version of ngDraggable.js. A droppable div is at the bottom, so usually you will be in a scrolled state. The result of the drop is a console.log output. You can easily experiment with it. Let me know if you have any questions.

**Comment by Cinetik** [comment] 2015-04-01 12:39
It works. I couldn't reproduce what you said about negative shrink on rectangle tho. Also, I would suggest to use $window or $document for the sack of using proper Angular wrappers (testability inside Angular app ++, see https://github.com/johnpapa/angular-styleguide#document-and-window).

**Comment by Remigius2011** [comment] 2015-04-01 13:12
I've created a pull request (and you seem to have seen it already).

There's another pull request for the same issue, as I have found out
meanwhile.

Regarding the bounding rectangle's bottom/right: effectively, you can
assign to it whatever you want - it will have no effect because the
rectangle as the result of getBoundingClientRect() is read-only (which
riddled me somewhat - subtracting $window.pageYOffset just did not have any
effect, although it was non zero).

**Comment by fatlinesofcode** [comment] 2015-04-10 00:41
is this fixed so, can we close this issue?

**Comment by Cinetik** [comment] 2015-04-10 06:28
seems so why the PR from @Remigius2011

**Comment by Remigius2011** [comment] 2015-04-10 07:32
Hi,

It could be considered cosmetic. Assignment to the bounding rectangle will
not have any effect, and using $window.page_Offset will possibly not work
in older browsers (which are not supported by current Angular versions
anyway - to be verified).

Cheers, R.

seems so why the PR from @Remigius2011 <https://github.com/Remigius2011>

—
Reply to this email directly or view it on GitHub
<https://github.com/fatlinesofcode/ngDraggable/issues/123#issuecomment-91449499>
.

**Closed** 2015-04-17 03:33 UTC
